# Generated by Django 3.0.8 on 2020-08-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=25, unique=True)),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='person.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_data', to='person.State')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('town', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_data', to='person.Town')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_data', to='person.State')),
            ],
        ),
    ]
